### ISSUE TITLE
New Update?

### ISSUE THREAD

**Issue by UglukOrc** [jeroentvb/spicetify-combined-playlists#21]
Any plans in the future on updating this?

**Comment by jeroentvb** [comment]
Updating for what? In its current state it does what I want it to do. So, what features are you missing?

**Comment by UglukOrc** [comment]
No sources are showing since Spotify's update months ago, So I stopped using it. I'm guessing it's bot up to par for Spotify's newer versions?

**Comment by jeroentvb** [comment]
That sounds strange. There are source playlists showing up for me. I'm using the latest spotify and spicetify. Can you open combined playlists and open the console to see what's going on?

**Comment by jeroentvb** [comment]
Haha, no worries. Glad you like it 😄
