### ISSUE TITLE
Only source code avalible

### ISSUE THREAD

**Issue by Jaycso** [jeroentvb/spicetify-combined-playlists#3]
Upon going to the realeases tab, there only appears to be source code, no compiled version. Is this intended or not? If this is just me looking in the wrong place then oops but I'm not sure.

**Comment by jeroentvb** [comment]
The compiled code is located in the [dist](https://github.com/jeroentvb/spicetify-combined-playlists/tree/dist) branch. Though I should probably include it in the release in the releases tab as well 😅 
Thanks for pointing this out.
