### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by theguyinyourbasement** [jeroentvb/spicetify-combined-playlists#6]
hey mine is broken I read it in a few other posts already and I wanted to uninstall it but I don't know how can anyone help pls?

**Comment by jeroentvb** [comment]
I've noticed that some of the functionality currently doesn't work 100%, and I'm looking into it.

In the meantime if you want to uninstall combined-playlists you can do the following:
1. In an terminal enter `spicetify config-dir`
2. Remove the `combined-playlists` folder
3. Open `config-xpui.ini`
4. Remove `combined-playlists` from the `custom_apps` entry, and save the file
5. Enter `spicetify apply` in a terminal window
